-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema b94votm47hggreb5kvpz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema b94votm47hggreb5kvpz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b94votm47hggreb5kvpz` DEFAULT CHARACTER SET utf8 ;
USE `b94votm47hggreb5kvpz` ;

-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`CALENDARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`CALENDARIO` (
  `ID_CALENDARIO` INT NOT NULL AUTO_INCREMENT,
  `DATA_CALENDARIO` DATETIME NOT NULL,
  `HUMOR_CALENDARIO` VARCHAR(200) NOT NULL,
  `ANOTACOES_CALENDARIO` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`ID_CALENDARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` (
  `ID_FORMAPAGTO` INT NOT NULL,
  `PIX_EMAIL_FORMAPAGTO` VARCHAR(100) NOT NULL,
  `PIX_CPF_FORMAPAGTO` VARCHAR(14) NOT NULL,
  `PIX_CHAVE_ALEATORIA_FORMAPAGTO` VARBINARY(32) NOT NULL,
  `PIX_CELULAR_FORMAPAGTO` CHAR(14) NOT NULL,
  `TOKEN_CARTAO_FORMAPAGTO` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_FORMAPAGTO`),
  UNIQUE INDEX `PIX_CHAVE_ALEATORIA_FORMAPAGTO_UNIQUE` (`PIX_CHAVE_ALEATORIA_FORMAPAGTO` ASC) VISIBLE,
  UNIQUE INDEX `PIX_CELULAR_FORMAPAGTO_UNIQUE` (`PIX_CELULAR_FORMAPAGTO` ASC) VISIBLE,
  UNIQUE INDEX `CARTAO_FORMAPAGTO_UNIQUE` (`TOKEN_CARTAO_FORMAPAGTO` ASC) VISIBLE,
  UNIQUE INDEX `PIX_EMAIL_FORMAPAGTO_UNIQUE` (`PIX_EMAIL_FORMAPAGTO` ASC) VISIBLE,
  UNIQUE INDEX `PIX_CPF_FORMAPAGTO_UNIQUE` (`PIX_CPF_FORMAPAGTO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`CONSULTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`CONSULTAS` (
  `ID_CONSULTAS` INT NOT NULL AUTO_INCREMENT,
  `DATAHORA_CONSULTAS` DATETIME NOT NULL,
  `STATUS_CONSULTAS` ENUM('Agendada', 'Realizada', 'Cancelada') NOT NULL,
  `PREFERENCIAS_REMOTAS_CONSULTAS` ENUM('Chat', 'Videochamada') NOT NULL,
  `ANOTACOES_CONSULTAS` MEDIUMTEXT NOT NULL,
  `VALOR_CONSULTA` DECIMAL(10,2) NOT NULL,
  `TEMPO_CONSULTA` VARCHAR(20) NOT NULL,
  `FORMA DE PAGAMENTO_ID_FORMAPAGTO` INT NOT NULL,
  PRIMARY KEY (`ID_CONSULTAS`),
  INDEX `fk_CONSULTAS_FORMA DE PAGAMENTO1_idx` (`FORMA DE PAGAMENTO_ID_FORMAPAGTO` ASC) VISIBLE,
  CONSTRAINT `fk_CONSULTAS_FORMA DE PAGAMENTO1`
    FOREIGN KEY (`FORMA DE PAGAMENTO_ID_FORMAPAGTO`)
    REFERENCES `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` (`ID_FORMAPAGTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`CHAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`CHAT` (
  `ID_CHAT` INT NOT NULL AUTO_INCREMENT,
  `MENSAGEM_CHAT` LONGTEXT NOT NULL,
  `DATA_HORA_CHAT` DATETIME NOT NULL,
  `STATUS_CHAT` ENUM('Online', 'Offline') NOT NULL,
  `CONSULTAS_ID_CONSULTAS` INT NOT NULL,
  PRIMARY KEY (`ID_CHAT`),
  INDEX `fk_CHAT_CONSULTAS1_idx` (`CONSULTAS_ID_CONSULTAS` ASC) VISIBLE,
  CONSTRAINT `fk_CHAT_CONSULTAS1`
    FOREIGN KEY (`CONSULTAS_ID_CONSULTAS`)
    REFERENCES `b94votm47hggreb5kvpz`.`CONSULTAS` (`ID_CONSULTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`COMENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`COMENTARIO` (
  `ID_COMENTARIO` INT NOT NULL AUTO_INCREMENT,
  `DATA_COMENTARIO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CURTIDAS_POSITIVAS_COMENTARIO` INT NOT NULL,
  `CURTIDAS_NEGATIVAS_COMENTARIO` INT NOT NULL,
  `TEXTO_COMENTARIO` MEDIUMTEXT NOT NULL,
  `STATUS_COMENTARIO` ENUM('normal', 'destaque', 'revisão') NOT NULL,
  PRIMARY KEY (`ID_COMENTARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`PAGAMENTO` (
  `ID_PAGAMENTO` INT NOT NULL AUTO_INCREMENT,
  `STATUS_PAGAMENTO` ENUM('Pago', 'Não Pago', 'Pendente') NOT NULL,
  `VALOR_PAGAMENTO` DECIMAL NOT NULL,
  `DATA_PAGAMENTO` DATETIME NOT NULL,
  `FORMA DE PAGAMENTO_ID_FORMAPAGTO` INT NOT NULL,
  PRIMARY KEY (`ID_PAGAMENTO`),
  INDEX `fk_PAGAMENTO_FORMA DE PAGAMENTO1_idx` (`FORMA DE PAGAMENTO_ID_FORMAPAGTO` ASC) VISIBLE,
  CONSTRAINT `fk_PAGAMENTO_FORMA DE PAGAMENTO1`
    FOREIGN KEY (`FORMA DE PAGAMENTO_ID_FORMAPAGTO`)
    REFERENCES `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` (`ID_FORMAPAGTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`PUBLICACAO COMUNIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`PUBLICACAO COMUNIDADE` (
  `ID_PUBLICACOMU` INT NOT NULL AUTO_INCREMENT,
  `ARQUIVOS_PUBLICACOMU` MEDIUMBLOB NOT NULL,
  `DATA_PUBLICACAO_PUBLICACOMU` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CURTIDAS_POSITIVAS_PUBLICACOMU` INT NOT NULL DEFAULT '0',
  `CURTIDAS_NEGATIVAS_PUBLICACOMU` INT NOT NULL DEFAULT '0',
  `TOPICOS_PUBLICACOMU` VARCHAR(200) NOT NULL,
  `URL_IMAGENS_POSTAGEM_PUBLICACOMU` VARCHAR(255) NOT NULL,
  `URL_IMAGENS_COMUNIDADE_PUBLICACOMU` VARCHAR(255) NOT NULL,
  `DATA_POSTAGEM_PUBLICACOMU` DATETIME NOT NULL,
  `COMENTARIO_ID_COMENTARIO` INT NOT NULL,
  PRIMARY KEY (`ID_PUBLICACOMU`),
  INDEX `fk_PUBLICACAO COMUNIDADE_COMENTARIO1_idx` (`COMENTARIO_ID_COMENTARIO` ASC) VISIBLE,
  CONSTRAINT `fk_PUBLICACAO COMUNIDADE_COMENTARIO1`
    FOREIGN KEY (`COMENTARIO_ID_COMENTARIO`)
    REFERENCES `b94votm47hggreb5kvpz`.`COMENTARIO` (`ID_COMENTARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`USUARIO` (
  `ID_USUARIO` INT NOT NULL,
  `NOME_USUARIO` VARCHAR(100) NOT NULL,
  `EMAIL_USUARIO` VARCHAR(100) NOT NULL,
  `SENHA_USUARIO` CHAR(60) NOT NULL,
  `DT_NASC_USUARIO` DATE NOT ,
  `DT_CRIACAO_CONTA_USUARIO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `RG_USUARIO` VARCHAR(20) NOT NULL,
  `CPF_USUARIO` VARCHAR(14) NOT NULL,
  `DIFERENCIACAO_USUARIO` ENUM('Comum', 'Menor de Idade') NOT NULL,
  `PSICOLOGO_ID_PSICOLOGO` INT NOT NULL,
  `PUBLICACAO COMUNIDADE_ID_PUBLICACOMU` INT NOT NULL,
  `CALENDARIO_ID_CALENDARIO` INT NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  UNIQUE INDEX `email` (`EMAIL_USUARIO` ASC) VISIBLE,
  INDEX `fk_USUARIO_PSICOLOGO_idx` (`PSICOLOGO_ID_PSICOLOGO` ASC) VISIBLE,
  INDEX `fk_USUARIO_PUBLICACAO COMUNIDADE1_idx` (`PUBLICACAO COMUNIDADE_ID_PUBLICACOMU` ASC) VISIBLE,
  INDEX `fk_USUARIO_CALENDARIO1_idx` (`CALENDARIO_ID_CALENDARIO` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_PSICOLOGO`
    FOREIGN KEY (`PSICOLOGO_ID_PSICOLOGO`)
    REFERENCES `b94votm47hggreb5kvpz`.`PSICOLOGO` (`ID_PSICOLOGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_PUBLICACAO COMUNIDADE1`
    FOREIGN KEY (`PUBLICACAO COMUNIDADE_ID_PUBLICACOMU`)
    REFERENCES `b94votm47hggreb5kvpz`.`PUBLICACAO COMUNIDADE` (`ID_PUBLICACOMU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_CALENDARIO1`
    FOREIGN KEY (`CALENDARIO_ID_CALENDARIO`)
    REFERENCES `b94votm47hggreb5kvpz`.`CALENDARIO` (`ID_CALENDARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`PLANOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`PLANOS` (
  `ID_PLANOS` INT NOT NULL AUTO_INCREMENT,
  `PERIODOS_PLANOS` ENUM('Mensal', 'Trimestral', 'Semestral', 'Anual') NOT NULL,
  `DATA_PLANOS` DATETIME NOT NULL,
  `STATUS_PLANOS` ENUM('Ativa', 'Inativa') NOT NULL,
  `USUARIO_ID_USUARIO` INT NOT NULL,
  `PAGAMENTO_ID_PAGAMENTO` INT NOT NULL,
  PRIMARY KEY (`ID_PLANOS`),
  INDEX `fk_PLANOS_USUARIO1_idx` (`USUARIO_ID_USUARIO` ASC) VISIBLE,
  INDEX `fk_PLANOS_PAGAMENTO1_idx` (`PAGAMENTO_ID_PAGAMENTO` ASC) VISIBLE,
  CONSTRAINT `fk_PLANOS_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `b94votm47hggreb5kvpz`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLANOS_PAGAMENTO1`
    FOREIGN KEY (`PAGAMENTO_ID_PAGAMENTO`)
    REFERENCES `b94votm47hggreb5kvpz`.`PAGAMENTO` (`ID_PAGAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`PSICOLOGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`PSICOLOGO` (
  `ID_PSICOLOGO` INT NOT NULL,
  `ESPECIALIDADE_PSICOLOGO` VARCHAR(100) NOT NULL,
  `PUBLICO_ALVO_PSICOLOGO` ENUM('Adulto', 'Criança', 'Idoso') NOT NULL,
  `BIOGRAFIA_PSICOLOGO` MEDIUMTEXT NOT NULL,
  `DISPONIBILIDADE_HORARIO_PSICOLOGO` DATE NOT NULL,
  `VALOR_CONSULTA_PSICOLOGO` DECIMAL(10,2) NOT NULL,
  `ESPECIALIDADE_PSICOLOGO` VARCHAR(200) NOT NULL,
  `TOPICOS_ABRANGENTES_PSICOLOGO` VARCHAR(200) NOT NULL,
  `ABORDAGEM_ABRANGENTE_PSICOLOGO` VARCHAR(200) NOT NULL,
  `PSICOLOGO_ID_PSICOLOGO` INT NOT NULL,
  `CONSULTAS_ID_CONSULTAS` INT NOT NULL,
  PRIMARY KEY (`ID_PSICOLOGO`),
  INDEX `fk_PSICOLOGO_PSICOLOGO1_idx` (`PSICOLOGO_ID_PSICOLOGO` ASC) VISIBLE,
  INDEX `fk_PSICOLOGO_CONSULTAS1_idx` (`CONSULTAS_ID_CONSULTAS` ASC) VISIBLE,
  CONSTRAINT `fk_PSICOLOGO_PSICOLOGO1`
    FOREIGN KEY (`PSICOLOGO_ID_PSICOLOGO`)
    REFERENCES `b94votm47hggreb5kvpz`.`PSICOLOGO` (`ID_PSICOLOGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PSICOLOGO_CONSULTAS1`
    FOREIGN KEY (`CONSULTAS_ID_CONSULTAS`)
    REFERENCES `b94votm47hggreb5kvpz`.`CONSULTAS` (`ID_CONSULTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
