-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema b94votm47hggreb5kvpz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema b94votm47hggreb5kvpz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b94votm47hggreb5kvpz` DEFAULT CHARACTER SET utf8 ;
USE `b94votm47hggreb5kvpz` ;

-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`PSICOLOGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`PSICOLOGO` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`PSICOLOGO` (
  `ID_PSICOLOGO` INT(11) NOT NULL,
  `ESPECIALIDADE_PSICOLOGO` VARCHAR(100) NOT NULL,
  `PUBLICO_ALVO_PSICOLOGO` ENUM('Adulto', 'Criança', 'Idoso') NOT NULL,
  `BIOGRAFIA_PSICOLOGO` MEDIUMTEXT NOT NULL,
  `DISPONIBILIDADE_HORARIO_PSICOLOGO` DATE NOT NULL,
  `VALOR_CONSULTA_PSICOLOGO` DECIMAL(10,2) NOT NULL,
  `TOPICOS_ABRANGENTES_PSICOLOGO` VARCHAR(200) NOT NULL,
  `ABORDAGEM_ABRANGENTE_PSICOLOGO` ENUM('Psicanálise, Humanista') NOT NULL,
  `PERMISSAO_ANOTACAO_USUARIO_PSICOLOGO` ENUM('Autorizado, Recusado') NOT NULL,
  PRIMARY KEY (`ID_PSICOLOGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`USUARIO_ADMINISTRADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`USUARIO_ADMINISTRADOR` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`USUARIO_ADMINISTRADOR` (
  `ID_USUARIO_ADM` INT NOT NULL,
  `INFORMACOES_DENUNCIAS_USUARIO_ADM` VARCHAR(100) NOT NULL,
  `STATUS_DENUNCIAS_USUARIO_ADM` ENUM('pendente', 'resolvida', 'rejeitada') NOT NULL,
  `VALOR_CUPONS_USUARIO_ADM` DECIMAL(5,2) NOT NULL,
  `STATUS_CUPONS_USUARIO_ADM` ENUM('ativo', 'inativo') NOT NULL,
  `STATUS_ASSINATURAS_CLIENTES_USUARIO_ADM` ENUM('Pago', 'Não Pago', 'Pendente') NOT NULL,
  `DURACAO_ASSINATURAS_CLIENTES_USUARIO_ADM` ENUM('semanal', 'mensal', 'anual') NOT NULL,
  `USUARIO_ID_USUARIO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_USUARIO_ADM`),
  CONSTRAINT `fk_USUARIO_ADMINISTRADOR_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `b94votm47hggreb5kvpz`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_USUARIO_ADMINISTRADOR_USUARIO1_idx` ON `b94votm47hggreb5kvpz`.`USUARIO_ADMINISTRADOR` (`USUARIO_ID_USUARIO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`USUARIO` (
  `ID_USUARIO` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME_USUARIO` VARCHAR(100) NOT NULL,
  `EMAIL_USUARIO` VARCHAR(100) NOT NULL,
  `SENHA_USUARIO` CHAR(60) NOT NULL,
  `DT_NASC_USUARIO` DATE NOT NULL,
  `DT_CRIACAO_CONTA_USUARIO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CPF_USUARIO` VARCHAR(14) NOT NULL,
  `DIFERENCIACAO_USUARIO` ENUM('Comum', 'Psicologo', 'Menor de Idade', 'Administrador') NOT NULL,
  `HORARIO_LOGIN_USUARIO` DATETIME NOT NULL,
  `HORARIO_LOGOUT_USUARIO` DATETIME NOT NULL,
  `USUARIO_ADMINISTRADOR_ID_USUARIO_ADM` INT NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  CONSTRAINT `fk_USUARIO_USUARIO_ADMINISTRADOR1`
    FOREIGN KEY (`USUARIO_ADMINISTRADOR_ID_USUARIO_ADM`)
    REFERENCES `b94votm47hggreb5kvpz`.`USUARIO_ADMINISTRADOR` (`ID_USUARIO_ADM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `email` ON `b94votm47hggreb5kvpz`.`USUARIO` (`EMAIL_USUARIO` ASC) VISIBLE;

CREATE UNIQUE INDEX `CPF_USUARIO_UNIQUE` ON `b94votm47hggreb5kvpz`.`USUARIO` (`CPF_USUARIO` ASC) VISIBLE;

CREATE INDEX `fk_USUARIO_USUARIO_ADMINISTRADOR1_idx` ON `b94votm47hggreb5kvpz`.`USUARIO` (`USUARIO_ADMINISTRADOR_ID_USUARIO_ADM` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`AGENDAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`AGENDAMENTO` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`AGENDAMENTO` (
  `idAGENDAMENTO` INT(11) NOT NULL AUTO_INCREMENT,
  `USUARIO_ID_USUARIO` INT(11) NOT NULL,
  `PSICOLOGO_ID_PSICOLOGO` INT(11) NOT NULL,
  PRIMARY KEY (`idAGENDAMENTO`),
  CONSTRAINT `fk_AGENDAMENTO_PSICOLOGO1`
    FOREIGN KEY (`PSICOLOGO_ID_PSICOLOGO`)
    REFERENCES `b94votm47hggreb5kvpz`.`PSICOLOGO` (`ID_PSICOLOGO`),
  CONSTRAINT `fk_AGENDAMENTO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `b94votm47hggreb5kvpz`.`USUARIO` (`ID_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_AGENDAMENTO_USUARIO1_idx` ON `b94votm47hggreb5kvpz`.`AGENDAMENTO` (`USUARIO_ID_USUARIO` ASC) VISIBLE;

CREATE INDEX `fk_AGENDAMENTO_PSICOLOGO1_idx` ON `b94votm47hggreb5kvpz`.`AGENDAMENTO` (`PSICOLOGO_ID_PSICOLOGO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`PLANOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`PLANOS` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`PLANOS` (
  `ID_PLANOS` INT(11) NOT NULL AUTO_INCREMENT,
  `PERIODOS_PLANOS` ENUM('Mensal', 'Trimestral', 'Semestral', 'Anual') NOT NULL,
  `DATA_PLANOS` DATETIME NOT NULL,
  `STATUS_PLANOS` ENUM('Ativa', 'Inativa') NOT NULL,
  PRIMARY KEY (`ID_PLANOS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`ASSINATURA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`ASSINATURA` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`ASSINATURA` (
  `idASSINATURA` INT(11) NOT NULL AUTO_INCREMENT,
  `PLANOS_ID_PLANOS` INT(11) NOT NULL,
  `USUARIO_ID_USUARIO` INT(11) NOT NULL,
  PRIMARY KEY (`idASSINATURA`),
  CONSTRAINT `fk_ASSINATURA_PLANOS1`
    FOREIGN KEY (`PLANOS_ID_PLANOS`)
    REFERENCES `b94votm47hggreb5kvpz`.`PLANOS` (`ID_PLANOS`),
  CONSTRAINT `fk_ASSINATURA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `b94votm47hggreb5kvpz`.`USUARIO` (`ID_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_ASSINATURA_PLANOS1_idx` ON `b94votm47hggreb5kvpz`.`ASSINATURA` (`PLANOS_ID_PLANOS` ASC) VISIBLE;

CREATE INDEX `fk_ASSINATURA_USUARIO1_idx` ON `b94votm47hggreb5kvpz`.`ASSINATURA` (`USUARIO_ID_USUARIO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`CALENDARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`CALENDARIO` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`CALENDARIO` (
  `ID_CALENDARIO` INT(11) NOT NULL AUTO_INCREMENT,
  `DATA_CALENDARIO` DATETIME NOT NULL,
  `HUMOR_CALENDARIO` VARCHAR(200) NOT NULL,
  `ANOTACOES_CALENDARIO` MEDIUMTEXT NOT NULL,
  `PSICOLOGO_ID_PSICOLOGO` INT(11) NOT NULL,
  `USUARIO_ID_USUARIO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_CALENDARIO`),
  CONSTRAINT `fk_CALENDARIO_PSICOLOGO1`
    FOREIGN KEY (`PSICOLOGO_ID_PSICOLOGO`)
    REFERENCES `b94votm47hggreb5kvpz`.`PSICOLOGO` (`ID_PSICOLOGO`),
  CONSTRAINT `fk_CALENDARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `b94votm47hggreb5kvpz`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_CALENDARIO_PSICOLOGO1_idx` ON `b94votm47hggreb5kvpz`.`CALENDARIO` (`PSICOLOGO_ID_PSICOLOGO` ASC) VISIBLE;

CREATE INDEX `fk_CALENDARIO_USUARIO1_idx` ON `b94votm47hggreb5kvpz`.`CALENDARIO` (`USUARIO_ID_USUARIO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`CHAT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`CHAT` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`CHAT` (
  `ID_CHAT` INT(11) NOT NULL,
  `MENSAGEM_CHAT` LONGTEXT NOT NULL,
  `DATA_HORA_CHAT` DATETIME NOT NULL,
  `STATUS_CHAT` ENUM('Online', 'Offline') NOT NULL,
  `MIDIA_CHAT` MEDIUMBLOB NULL,
  `DOCUMENTOS_CHAT` MEDIUMBLOB NULL,
  PRIMARY KEY (`ID_CHAT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`PUBLICACAO COMUNIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`PUBLICACAO COMUNIDADE` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`PUBLICACAO COMUNIDADE` (
  `ID_PUBLICACOMU` INT(11) NOT NULL AUTO_INCREMENT,
  `ARQUIVOS_DIVERSOS_PUBLICACOMU` MEDIUMBLOB NOT NULL,
  `DATA_PUBLICACAO_PUBLICACOMU` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CURTIDAS_POSITIVAS_PUBLICACOMU` INT(11) NOT NULL DEFAULT '0',
  `CURTIDAS_NEGATIVAS_PUBLICACOMU` INT(11) NOT NULL DEFAULT '0',
  `TOPICOS_POSTAGEM_PUBLICACOMU` VARCHAR(200) NOT NULL,
  `IMAGENS_POSTAGEM_PUBLICACOMU` MEDIUMBLOB NOT NULL,
  `IMAGENS_COMUNIDADE_PUBLICACOMU` MEDIUMBLOB NOT NULL,
  `DATA_POSTAGEM_PUBLICACOMU` DATETIME NOT NULL,
  `LISTA_MODIFICACOES_PUBLICACOMU` VARCHAR(250) NULL,
  `NOME_COMUNIDADE_PUBLICACOMU` VARCHAR(100) NOT NULL,
  `BIOGRAFIA_COMUNIDADE_PUBLICACOMU` MEDIUMTEXT NOT NULL,
  `ABORDAGEM_COMUNIDADE_PUBLICACOMU` ENUM(' Psicanálise, Humanista') NOT NULL,
  `TITULO_POSTAGEM_PUBLICACOMU` VARCHAR(100) NOT NULL,
  `COMUNIDADES_DISPONIVEIS_POSTAGEM_PUBLICACOMU` LONGTEXT NOT NULL,
  `USUARIO_ID_USUARIO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_PUBLICACOMU`),
  CONSTRAINT `fk_PUBLICACAO COMUNIDADE_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `b94votm47hggreb5kvpz`.`USUARIO` (`ID_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_PUBLICACAO COMUNIDADE_USUARIO1_idx` ON `b94votm47hggreb5kvpz`.`PUBLICACAO COMUNIDADE` (`USUARIO_ID_USUARIO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`COMENTARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`COMENTARIO` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`COMENTARIO` (
  `ID_COMENTARIO` INT(11) NOT NULL AUTO_INCREMENT,
  `DATA_COMENTARIO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CURTIDAS_POSITIVAS_COMENTARIO` INT(11) NOT NULL,
  `CURTIDAS_NEGATIVAS_COMENTARIO` INT(11) NOT NULL,
  `TEXTO_COMENTARIO` MEDIUMTEXT NOT NULL,
  `STATUS_COMENTARIO` ENUM('normal', 'destaque', 'revisão') NOT NULL,
  `RESULTADO_ENQUETE` DECIMAL(5,2) NOT NULL,
  `PUBLICACAO COMUNIDADE_ID_PUBLICACOMU` INT(11) NOT NULL,
  PRIMARY KEY (`ID_COMENTARIO`),
  CONSTRAINT `fk_COMENTARIO_PUBLICACAO COMUNIDADE1`
    FOREIGN KEY (`PUBLICACAO COMUNIDADE_ID_PUBLICACOMU`)
    REFERENCES `b94votm47hggreb5kvpz`.`PUBLICACAO COMUNIDADE` (`ID_PUBLICACOMU`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_COMENTARIO_PUBLICACAO COMUNIDADE1_idx` ON `b94votm47hggreb5kvpz`.`COMENTARIO` (`PUBLICACAO COMUNIDADE_ID_PUBLICACOMU` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`CONSULTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`CONSULTAS` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`CONSULTAS` (
  `ID_CONSULTAS` INT(11) NOT NULL AUTO_INCREMENT,
  `DATAHORA_CONSULTAS` DATETIME NOT NULL,
  `STATUS_CONSULTAS` ENUM('Agendada', 'Realizada', 'Cancelada') NOT NULL,
  `PREFERENCIAS_REMOTAS_CONSULTAS` ENUM('Chat', 'Videochamada') NOT NULL,
  `ANOTACOES_CONSULTAS` MEDIUMTEXT NOT NULL,
  `VALOR_CONSULTA` DECIMAL(10,2) NOT NULL,
  `TEMPO_CONSULTA` VARCHAR(20) NOT NULL,
  `USUARIO_ID_USUARIO` INT(11) NOT NULL,
  `PSICOLOGO_ID_PSICOLOGO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_CONSULTAS`),
  CONSTRAINT `fk_CONSULTAS_PSICOLOGO1`
    FOREIGN KEY (`PSICOLOGO_ID_PSICOLOGO`)
    REFERENCES `b94votm47hggreb5kvpz`.`PSICOLOGO` (`ID_PSICOLOGO`),
  CONSTRAINT `fk_CONSULTAS_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `b94votm47hggreb5kvpz`.`USUARIO` (`ID_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_CONSULTAS_USUARIO1_idx` ON `b94votm47hggreb5kvpz`.`CONSULTAS` (`USUARIO_ID_USUARIO` ASC) VISIBLE;

CREATE INDEX `fk_CONSULTAS_PSICOLOGO1_idx` ON `b94votm47hggreb5kvpz`.`CONSULTAS` (`PSICOLOGO_ID_PSICOLOGO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` (
  `ID_FORMAPAGTO` INT NOT NULL AUTO_INCREMENT,
  `PIX_EMAIL_FORMAPAGTO` VARCHAR(100) NOT NULL,
  `PIX_CPF_FORMAPAGTO` VARCHAR(14) NOT NULL,
  `PIX_CHAVE_ALEATORIA_FORMAPAGTO` VARBINARY(32) NOT NULL,
  `PIX_CELULAR_FORMAPAGTO` VARCHAR(14) NOT NULL,
  `TOKEN_CARTAO_FORMAPAGTO` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_FORMAPAGTO`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `PIX_CPF_FORMAPAGTO_UNIQUE` ON `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` (`PIX_CPF_FORMAPAGTO` ASC) VISIBLE;

CREATE UNIQUE INDEX `PIX_EMAIL_FORMAPAGTO_UNIQUE` ON `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` (`PIX_EMAIL_FORMAPAGTO` ASC) VISIBLE;

CREATE UNIQUE INDEX `PIX_CHAVE_ALEATORIA_FORMAPAGTO_UNIQUE` ON `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` (`PIX_CHAVE_ALEATORIA_FORMAPAGTO` ASC) VISIBLE;

CREATE UNIQUE INDEX `PIX_CELULAR_FORMAPAGTO_UNIQUE` ON `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` (`PIX_CELULAR_FORMAPAGTO` ASC) VISIBLE;

CREATE UNIQUE INDEX `TOKEN_CARTAO_FORMAPAGTO_UNIQUE` ON `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` (`TOKEN_CARTAO_FORMAPAGTO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`PAGAMENTO_PLANOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`PAGAMENTO_PLANOS` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`PAGAMENTO_PLANOS` (
  `ID_PAGAMENTOPLANOS` INT NOT NULL,
  `STATUS_PAGAMENTOPLANOS` ENUM('Pago, Não Pago, Pendente') NOT NULL,
  `VALOR_PAGO_PAGAMENTOPLANOS` DECIMAL NOT NULL,
  `DATA_PAGAMENTO_PAGAMENTOPLANOS` DATETIME NOT NULL,
  `PLANOS_ID_PLANOS` INT(11) NOT NULL,
  `CUPOM_PLANOS` ENUM('usado', 'não usado', 'expirado') NOT NULL,
  `FORMA DE PAGAMENTO_ID_FORMAPAGTO` INT NOT NULL,
  PRIMARY KEY (`ID_PAGAMENTOPLANOS`, `FORMA DE PAGAMENTO_ID_FORMAPAGTO`),
  CONSTRAINT `fk_PAGAMENTO_PLANOS_PLANOS1`
    FOREIGN KEY (`PLANOS_ID_PLANOS`)
    REFERENCES `b94votm47hggreb5kvpz`.`PLANOS` (`ID_PLANOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAGAMENTO_PLANOS_FORMA DE PAGAMENTO1`
    FOREIGN KEY (`FORMA DE PAGAMENTO_ID_FORMAPAGTO`)
    REFERENCES `b94votm47hggreb5kvpz`.`FORMA DE PAGAMENTO` (`ID_FORMAPAGTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PAGAMENTO_PLANOS_PLANOS1_idx` ON `b94votm47hggreb5kvpz`.`PAGAMENTO_PLANOS` (`PLANOS_ID_PLANOS` ASC) VISIBLE;

CREATE INDEX `fk_PAGAMENTO_PLANOS_FORMA DE PAGAMENTO1_idx` ON `b94votm47hggreb5kvpz`.`PAGAMENTO_PLANOS` (`FORMA DE PAGAMENTO_ID_FORMAPAGTO` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `b94votm47hggreb5kvpz`.`AVALIACOES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b94votm47hggreb5kvpz`.`AVALIACOES` ;

CREATE TABLE IF NOT EXISTS `b94votm47hggreb5kvpz`.`AVALIACOES` (
  `ID_AVALIACOES` INT NOT NULL AUTO_INCREMENT,
  `REVIEW_CONSULTA_AVALIACOES` MEDIUMTEXT NULL,
  `MEDIA_ESTRELAS_AVALIACOES` FLOAT NULL,
  `AVALIACAO_ESTRELAS` INT NULL,
  `CONSULTAS_ID_CONSULTAS` INT(11) NOT NULL,
  PRIMARY KEY (`ID_AVALIACOES`),
  CONSTRAINT `fk_AVALIACOES_CONSULTAS1`
    FOREIGN KEY (`CONSULTAS_ID_CONSULTAS`)
    REFERENCES `b94votm47hggreb5kvpz`.`CONSULTAS` (`ID_CONSULTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_AVALIACOES_CONSULTAS1_idx` ON `b94votm47hggreb5kvpz`.`AVALIACOES` (`CONSULTAS_ID_CONSULTAS` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
